### ISSUE TITLE
typo in guide page and result file!!

### ISSUE THREAD

**Issue by av930** [LG-Electronics/android-dependency-scanning#1]
1. guide page typo: 
classpath 'com.lge.android.licensetools:**android-dependency-scanning:0.2.0'**

2. result file typo:
"ID"	Source Name or Path	OSS Name	OSS Version	License	Download Location	Homepage	Copyright Text	License Text	Exclude	Comment
-	[Name of the Source File or Path]	[Name of the OSS used in the Source Code]	[Version Number of the OSS]	[License of the OSS. Use SPDX Identifier : https://spdx.org/licenses/]	[Download URL or a specific location within a VCS for the OSS]	[Web site that serves as the OSS's home page]	[The copyright holders of the OSS]	[License Text of the License. This field can be skipped if the License is in SPDX.]	[If this OSS is not included in the final version, Exclude]	
1	**build.gralde**	Android Support Library compat	27.1.0	The Apache Software License, Version 2.0	https://mvnrepository.com/artifact/com.android.support/support-compat/27.1.0	http://developer.android.com/tools/extras/support-library.html		http://www.apache.org/licenses/LICENSE-2.0.txt
2	**build.gralde**	Android Support Library media compat	27.1.0	The Apache Software License, Version 2.0	https://mvnrepository.com/artifact/com.android.support/support-media-compat/27.1.0	http://developer.android.com/tools/extras/support-library.html		http://www.apache.org/licenses/LICENSE-2.0.txt

3. please add path of output file 
and It would be more great if print where the output file is generated.
I spent some time to find output file.

**Comment by dd-lge** [comment]
Hi,
Thank you for your attention.
I updated guide page and result file type.
And lastly, I updated the path of output file in guide page and also I added to print the path of output file.
